import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/features/sidebar/sidebar";
import { PageTitle } from "@/components/page-title";
import { EmailContextProvider } from "@/contexts/email-context";
import { Modal } from "@/components/modal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          display: "flex",
          position: "relative",
        }}
      >
        <EmailContextProvider>
          <Sidebar />
          <div>
            <PageTitle />

            <div>{children}</div>
            <Modal />
          </div>
        </EmailContextProvider>
      </body>
    </html>
  );
}
